name: Github Action for Typst
description: GitHub Action to compile typst documents
author: Louis Vignoli
branding:
  icon: book-open
  color: blue

inputs:
  source_file:
    description: >
      The typst file to be compiled. There can be multiple ones separated by new lines.
    required: true
  options:
    description: >
      Line separated array of global options to pass to typst. Compared to a CLI call, with space
      separated field, each file must be on its own lines. For example, to pass an additional font
      path using the --font-path global command, the CLI call is

        typst --font-path fonts main.typ

      For the action, one must use one line per argument to ensure correct parsing, in the following
      form:

        - name: Typst
          uses: lvignoli/typst-action@main
          with:
            source_file: main.typ
            options: |
              --font-path
              fonts
    required: false
    default: ""
  prepare_commands:
    description: >
      A set of commands to execute before the typst command is run.
      An example use-case is to install fonts.
      The commands will be passed to /bin/bash as they are. 
      Use with caution.

      - name: Typst
          uses: lvignoli/typst-action@main
          with:
             source_file: main.typ
             prepare_commands: |
                sudo apt install fonts-ibm-plex
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.source_file }}
    - ${{ inputs.options }}
    - ${{ inputs.prepare_commands }}
